// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

var input = Belt_Array.range(1, 100);

function fizzBuzz(input) {
  return input;
}

console.log(input);

export {
  input ,
  fizzBuzz ,
  
}
/* input Not a pure module */
